Algoritmo "somador"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Danilo Rodrigues de oliveira
// Data atual  : 24/12/2021
Var
// Seção de Declarações das variáveis 
   n, cont, s: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   s <- 0
   cont <- 1
   Enquanto (cont <= 5) faca

   FimEnquanto

Fimalgoritmo